#!/usr/bin/env bash
# Transfers a file to a remote server's home directory via SCP

# Check for correct number of arguments
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE=$1
IP=$2
USER=$3
KEY=$4

# Perform the secure copy
scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USER@$IP:~/"
